name: Android CI
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r26d

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Compiling
        run: |
          haxelib git raylib-hx https://github.com/foreignsasquatch/raylib-hx.git android --quiet --skip-dependencies
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git --quiet
          cd $(haxelib libpath hxcpp)/tools/hxcpp
          haxe compile.hxml
          cd ${{github.workspace}}
          ./build.sh
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: project/app/build/outputs/apk/debug
          if-no-files-found: warn
