name: Android CI
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Compiling
        run: |
          haxelib git raylib-hx https://github.com/MAJigsaw77/raylib-hx.git --quiet --skip-dependencies
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git --quiet
          cd $(haxelib libpath hxcpp)/tools/hxcpp
          haxe compile.hxml
          cd ${{github.workspace}}
          chmod +x ./build.sh && ./build.sh
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: project/app/build/outputs/apk/debug
          if-no-files-found: warn
  
